name: redux_dart
version: 0.0.1
description: >
  A good to use redux lib for dart.
author: lestathc
homepage: https://github.com/lestathc/redux-dart
dependencies:
  rxdart: ^0.8.3
dev_dependencies:
  browser: ^0.10.0
  react: ^0.8.5
  test: 0.12.19
  coverage: ^0.9.2
